apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels: 
    app: web-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: web-app
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 20%
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: stevenmoyes/lbg-python-api-base:latest
          imagePullPolicy: Always
          ports: 
            - containerPort: 5500
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: ClusterIP
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 5500  
      targetPort: 5500